; generated by PrusaSlicer 2.6.0+MacOS-arm64 on 2023-07-07 at 15:32:08 UTC


;
; thumbnail begin 16x16 428
; iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABCElEQVR4AbWSu26DMBSG/aBcBOWWCO
; pQCuqC1IEKlSWiUi9bK3XtU3Tp3Cf6k2N0iIkwZMnwDZb9f8f2OcKyLJh46/eKpTPCtPH/9zuyJBFr
; 4TWRsG0bjCmo8/6yH88rQZqmcF33orAuITzPg+j7Hg/3BX6+Py8WfH28Ig5u0DQNBFUvdrdoH2slWR
; Pttoki227gOM7wB4UcBMychKpymNhE4UlwJ7OJ4FyiBxl6AmWNAmYufB2BSWIS8CxMBmlOshSeCKid
; Uko8PzVGQdd1qOsaURSpDowCWmTZsXrboixLNWF8G71qkiSgwauqCr7vD22kykEQII5jFWQzP4k/S7
; 9pGIbI81ytD75dfsGa+Xn6AAAAAElFTkSuQmCC
; thumbnail end
;

;
; thumbnail begin 220x124 5144
; iVBORw0KGgoAAAANSUhEUgAAANwAAAB8CAYAAAACRt5vAAAO2UlEQVR4Ae3dh1MUTRoGcP5QMyiKIp
; jLgFnPrIeIh5aKYtYy1KlYimLOOeecc47Ae/X01fDN7g7L7kx3T78z71Q9VV+AZbanf9s9HWZLevTo
; QRKJxE5KOJ2s5J/U/3shq/OV/D8CjlkA7fLJIyqCjl8EHKN40PwRdLwi4JgkCJvA4xcB53i6gyboeK
; WkqqqK1QmnKcVg86MTeO6mZN26ddSrVy9WJ530+AdGwkbQuZXevXvT3r17qeTevXs0ePBgVief5ESF
; JujczPDhw+n27dtUMnv2bOrXrx+rk09qdGITeO5ly5YtVCLdyfhjCpqgcy+Bo5Ro8Xr27Cn3dhZiA5
; vAs5t8bjLA4cZu586ddPfuXbp//z41NzfTjBkz1H938Y1xjo6BEUHnVvr370+7d++ms2fPqowbNy7n
; ZzLATZ48mZ4+fUodHR2Eo62tTf376tWraejQoWzeuOuJC1o2OoGnL3PnzqXv378rM97x8uVLGjVqVM
; bPZYAbNGiQkpl9fPjwgY4dO6ZAcnjzLscFbNLa6UufPn3o4MGDOWb+/v1LN27coGHDhmX8fAY49D1r
; amro1KlT9OPHj4wX+P37Nz148ICWLFlCAwYMYFMgrsQ1aIIuesaOHUuvX7+moOPZs2c0YsSInN8JHD
; SprKykTZs2qV/KPt68eUN79uxRf8z1AnElLmMTeOECH+3t7YHYMMHd1cBJl2spMVI5a9YsunLlimoe
; /Qf6qtevX1f9VjSprhdOXOECTdAVnoqKCjWBHXR8+fKFZs6cmff38y5extQAmkWMVr579y7jxaH7+f
; PntGHDhpx+qoQnNj86gZeburo6+vnzZyC28+fPU2lpabevUdBuAdyz4d4Nsr0RTO/49OkTnT59mqZN
; m5b6eTt8QC2tXUhxg9EVvBe8J07XwETQ2ztx4kQgNIxtLFu2rODXKnh7DubiMK9w9OhR+vr1a8YfRZ
; fz8ePH6g9jpNO1AjMRVMTscMJULLrscLpWUTJlyhQ1Sh90YBCx2OmyovfDoQ/b1NSkgGUf6Ha2tLTQ
; hAkTnCo0HQmqdEnHVgi8pALEe8IikK6O7du3h3rfoTag9u3bl6ZPn04XLlxQTar/QB/31q1btHDhQv
; VzLhRelEJPO7Ri0CUFX3V1NT169CgQ2vv372nSpEmhXzv0jm8ULE4MnwLZcxG4z8O2H44tXSEVKo3Y
; /OgKhccRH5YyYlwi6MDij6iNSORHLJSVldGiRYvUrLp/XgInjRFMDoVeDLKkDYxEgVdsubleD4Bp27
; Zt9O3bt5xeW21trZa/oeWZJhidHD16tDrZJ0+eqAlzrFbB/Z7NAismxVaWNLdq+dCFgecqPtTjefPm
; qTlmjEe8ePGCrl69qnUgUOtDhHDCGM3ECbpaqGGhCbb88MKWqYt1ZMiQIWr+GbdMul/b2lO7ULiYzx
; g4cKD6Z5tzdlGQCTTz6OLAhxVS+Ju2t55ZAYc3h20Khw4doo8fP9KlS5do/fr1qhtq8u9GrQCCLZnw
; Vq5cSWfOnFGrQzC8b7oeWgeHlg3zc1iD6R24MUX/GGvPdH/K6IAmAyPxojMBD7c6GNzzRtK9erhq1S
; qj9d86OAQLobOnDzCqiWVhup4apuMiS6umD51L8PD81YsXL+YM9WPB8dKlS63d4lgDh+mD+vp69fgG
; 79MFe+5QCFF3k+uCJq2aGXi6rk+U+oHH1N25cycD258/f1T30pYBq+AQdB3RX16zZg1dvnyZdu3a1e
; 12BhvQpFXjgy4sPCzAx2p/rI7CsD/WBMexyyWW7xbQ9akl2NILL0ydQbcRk9vYRhOl7rEDly8oEHzy
; YGcCJs6zl9IINEGXDx5uXTAmgLoTFyoW4FA4aPY3b95Mb9++VQMq2JGwdetWGjlypNaLJNjiR2cCXk
; NDg3q8IzZGY/ExvjfDtefvONXCjR8/vhObd3z+/FnNl3jTB1EvjAyMuAVPBza0aufOncsZgcTjQbBa
; xKWWzilw6FvjAUVA5j/wrD+s0VyxYoVadhPl4mxtWsWqUiY51RUDI2PD6v7s+uJNOe3bt09hdKmOO3
; cPh753Y2MjPXz4MKcQsReptbWVJk6cGPoC/WtyjUIn8OLHFgUcejt41k7QAWy4NXGtbjsJDsFAydSp
; U1U34devXxmFiX/HXB62S+DR0mHAeRF09tP4nyWd2MKCwz09nggedOAxjrg1cakb6Sy47ILF6gBs+c
; Ejo7OPV69eqc2vmNcLC05aO7vxQwsLDnO42Y9t9A70frxFyf64VMedGqXs6oZ4/vz5dO3atYzntuPA
; w4xwY4zvuAsq6ELASWsXH7ZiwJWXl6s6EHRgxRLqSL7fd6WeOwGuu8LGhCV2G2ABdPYTlNBfx4ZXPN
; gILWJYcILOLrRiwAFT9qP3vQMIgbGQ13GhrscOrpjuBPbS4VF8eF5K9oFtP8ePH1ePNQsLTuDZxdYd
; ONzLo5sYdKBbie5lMfXHBXSxgiu2sBB0HTFKefLkyYztPjiwGBXPCsTqb2+jaxhwgi5asgdGwoDDwA
; cGQIIO9GiiLIZIJbiwheUFXziycePGLr9wBF+oMGbMmNDgZEAlXAqFlg8chvS7+qIMTAXoWACRKnBR
; C8sLJsqxzw47D7JHrjAZiony7MGUYsBJa1d4imnVugKHa4UnAQTdr+F6YpJbV92JC511cDoLDMGAiv
; eFI1gWhgP77dDdXLt2rRZwgi5/wkALAocnAxw4cKATmdfKYT4Wo9W6604c6KyCM1FgXrBIFY8427Fj
; h1p7uXjx4s5tGDrACTz92IK6lFhpdOTIEbW4AdcRXyJjst7YRmf1qV22gj4+Wr6g/xcVnKDTA627QR
; P0TAqdW+WEzgo4W4XWXfAoBx3g0j6gogtbPnBxJBHgXClMbO/B4IoucGls7cIOjOQL7s8KnbhOAjqj
; 4FwpRHQvMdSMkUzd4NKCTjc0L1g5hPu0rm4BkoYuFeAQTJSaaOHSAM8UNgRzpjU1NU7VFZbgXCpABJ
; +gmAg3CS5p6ExC8+J9D4VrYQXOxQL0YhpcUuDZwObaoIkNdNrBuVyANsFxRWdiYIQrOBPoBJwFdFzg
; 2YQm4FKALQ5wXFq7OLBxAKcbnTZwHAouTnCuoosLGidwOtEJuBTDixubgEs4NlfAxY3OBWjcwOlCJ+
; BiRmcbnkvYBFzCsbkGzmZrZ3u4P4ngdKATcClA5yI0AZcCbC6DMwXPZWwcwUVFJ+ASis51aAIuBdi4
; gPPQhYXHBRtXcFHQCbgEtXauDowIOAHHDl138DghE3ApwcYVXHetHSdgSQEXFp2AY4yOEywBJ+BYhx
; MqARcBHKcCEXACzjV0Ao5pOKEScAKOfTihEnACjn04oRJwIcFxKggBxyOc6o4OdAKOaTihEnACjn04
; oRJwAo59OKEScAKOfTihEnACjn04oRJwAo59OKEScCHAcSoAAccnnOqODnQCjmk4oRJwAo59OKEScC
; kGN7yqkhWsJIMrLytlVXcEXAR03OFxgpXklk3AFQmPE7KkgONURwScoGMLjlO9iB1cktFxhMcJmmAT
; cOzRcYGWpIERAWcIHQd4HLBxuu5RIuA0wRNw0qoVEgGXAnSuYuN0fXVFwKUAnmBzJwIuBegEmjsxBk
; 7QuTOgItjcSLF+BFyIuIAubmhpGxjpKgLOUuJu7eLExuk6mY6As5y40Ak2N2IcnKDLTRzoBFr8CWNH
; wGlKr169qKG+LpHgxo8fz+pa2IqAiylDhw6l+/fvE46jrQcTA65513/px48fdPPmTZo/fz7169eP1X
; UxHWvgBN0/aWhooN+/f5P/ALrDB1tYg/MfHR0d9OLFC9qyZQuNGDGC1fUxlbBuBFzIlJWV0dmzZyno
; +PXrF9XX1xu9tzOJbfHixXTr1i1qb2/PeF+fP3+m8+fP08yZM6l3796srpfuWAeXZnQzZsxQlS/ouH
; v3Lg0ZMqTzZ02hMwHNO2dgGjt2LB0+fDjnfba1tdGTJ09oxYoVGe8zTYliRsAVEVTEPXv2BEJDa4Au
; V1e/qxueKWz+VFRU0OrVq+nRo0c57/f9+/fU2tpKEydOdP666Y6As5CRI0fS06dPA7G9ffuWJkyY0O
; 1r6ERnEpo/ffv2palTp9K5c+dUVzm764wWvba2lvr37+/stdOd2MClBR0+5f/+/RuI7dChQ6pSFvpa
; ulao2MDmT3V1NW3fvp1evnyZUwavXr2inTt30pgxY5y6biYS1YuAy5Py8nK6evVqIDQMly9YsCD0a0
; dFFwVa2HWQGCjC9MD169fVvZz/+Pr1K125coVmz55Nffr0ifW6mUzs4JKKDhXr+/fvgdiuXbtGAwdG
; X30RBZ2NVi0omOAfPXo0HThwgD58+JBRLriPffbsGa1Zs4aqqqqsXzPT0WFFC7gkoUP3EIMBQQe6lU
; 1NTdr/Zhh4cWDzBx84y5cvp3v37uWU08ePH+n48eM0adIko9fKZnQ5EXC+DBo0iE6fPh2IDZ/co0aN
; Mva3i0UXFzR/0HXEKOWpU6dyegMYUEEriG65qb9vM86BSwI6LNHChG/2sXfvXmsTvYXCixubP5WVlb
; Rp0yb1oeQdP3/+pAsXLqj/Z+McTEanEQHnC4a2sULkxo0bau7p9u3balWF7fMoBJ2pgZGwKS0tVdMH
; u3fvpgcPHtD+/fvVAIrtsjMRZ8ElAR1aMizSRVcoztG27qYP4m7VugoGVVCGSVn6pduHdnAc0KEyoD
; XjMFnbFToXsXUXDEjhPhkDLrgGwOny+ZqwkTpwU6ZMUfcWWCGBbSeNjY2qO+TyOQeh4wQNwYcb7vPe
; vHmj7u8uXrxIdXV1avmYq+fMBpyL6PBpumPHjozBEGw7wSQuly0nfnicsCH4oMN0gX8Hwrt376ilpU
; WtYnHtfE25MAbOJXTovqxcuVKtfAcy/7zaiRMnnP6UzY6HLo6BkShBL6K5uTlnPSauyaJFi5zqXpo0
; YRScS+jWrl3biQ3LkpBjx46x3MUMdJzO1wumXbDm8vXr153gsLEVW31cWQ5m2oNxcK6gw406WjlsoM
; SQ9Zw5c5w4r7QF93KYLN+4caPa6jRv3jwaMGCAE+dmw8L/AAsxtPpAA4ukAAAAAElFTkSuQmCC
; thumbnail end
;
; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R2
M201 X2500 Y2500 Z400 E5000 ; sets maximum accelerations, mm/sec^2
M203 X180 Y180 Z12 E80 ; sets maximum feedrates, mm / sec
M204 P2000 R1250 T2500 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z2.00 E10.00 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
;TYPE:Custom
M862.3 P "MINI" ; printer model check
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S170 ; set extruder temp for bed leveling
M140 S100 ; set bed temp
M109 R170 ; wait for bed leveling temp
M190 S100 ; wait for bed temp
M204 T1250 ; set travel acceleration
G28 ; home all without mesh bed level
G29 ; mesh bed leveling 
M204 T2500 ; restore travel acceleration
M104 S255 ; set extruder temp
G92 E0
G1 Y-2 X179 F2400
G1 Z3 F720
M109 S255 ; wait for extruder temp

; intro line
M73 P3 R2
G1 X170 F1000
G1 Z0.2 F720
G1 X110 E8 F900
G1 X40 E10 F700
G92 E0

M221 S95 ; set flow
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.2 ; Filament gcode
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


M73 P6 R2
G1 E-2.7 F4200
M73 P10 R2
G1 Z.2 F720
;AFTER_LAYER_CHANGE
;0.2

; Filament-specific end gcode
G1 E-1 F2100 ; retract
G1 Z7 F720 ; Move print head up
G1 X178 Y178 F4200 ; park print head
G1 Z35 F720 ; Move print head further up
G4 ; wait
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M221 S100 ; reset flow
M900 K0 ; reset LA
M84 ; disable motors
; max_layer_z = 5
M73 P100 R0
; filament used [mm] = 73.49
; filament used [cm3] = 0.18
; filament used [g] = 0.18
; filament cost = 0.01
; total filament used [g] = 0.18
; total filament cost = 0.01
; estimated printing time (normal mode) = 2m 29s
; estimated first layer printing time (normal mode) = 31s

; prusaslicer_config = begin
; autoemit_temperature_commands = 1
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,180x0,180x180,0x180
; bed_temperature = 100
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 25
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; color_change_gcode = M600
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.4";"printer_model==\"MINI\" and nozzle_diameter[0]!=0.8"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MINI
; deretract_speed = 40
; disable_fan_first_layers = 4
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 1
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G1 E-1 F2100 ; retract\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)} F720 ; Move print head up{endif}\nG1 X178 Y178 F4200 ; park print head\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+30, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM221 S100 ; reset flow\nM900 K0 ; reset LA\nM84 ; disable motors\n; max_layer_z = [max_layer_z]
; external_perimeter_acceleration = 800
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 30
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 35
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 0
; fan_below_layer_time = 30
; filament_colour = #FFF2EC
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 27.82
; filament_density = 1.04
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 10
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 5.70968 6.03226 7 8.25806 9 9.19355 9.3871 9.77419 10.129 10.3226 10.4516 10.5161| 0.05 5.69677 0.45 6.15484 0.95 8.76774 1.45 9.20323 1.95 9.95806 2.45 10.3871 2.95 10.5677 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_before_travel = 3
; filament_retract_length = 2.7
; filament_settings_id = "Generic ABS @MINI"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = ABS
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; filament_wipe = 0
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 600
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 100
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 255
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin2
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; infill_acceleration = 1500
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_overlap = 10%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 2000
; machine_max_acceleration_retracting = 1250
; machine_max_acceleration_travel = 2500
; machine_max_acceleration_x = 2500
; machine_max_acceleration_y = 2500
; machine_max_acceleration_z = 400
; machine_max_feedrate_e = 80
; machine_max_feedrate_x = 180
; machine_max_feedrate_y = 180
; machine_max_feedrate_z = 12
; machine_max_jerk_e = 10
; machine_max_jerk_x = 8
; machine_max_jerk_y = 8
; machine_max_jerk_z = 2
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 15
; max_layer_height = 0.25
; max_print_height = 180
; max_print_speed = 150
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 15
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{printing_filament_types}_{printer_model}_{print_time}.gcode
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 900
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 40
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.20mm QUALITY @MINI
; printer_model = MINI
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MINI\n
; printer_settings_id = Original Prusa MINI & MINI+
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1.5
; retract_before_wipe = 70%
; retract_layer_change = 1
; retract_length = 3.2
; retract_length_toolchange = 4
; retract_lift = 0.2
; retract_lift_above = 0
; retract_lift_below = 179
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 70
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 20
; small_perimeter_speed = 25
; solid_infill_acceleration = 1500
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if nozzle_diameter[0]==0.6}0.12{elsif nozzle_diameter[0]==0.8}0.06{else}0.2{endif} ; Filament gcode"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S170 ; set extruder temp for bed leveling\nM140 S[first_layer_bed_temperature] ; set bed temp\nM109 R170 ; wait for bed leveling temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM204 T1250 ; set travel acceleration\nG28 ; home all without mesh bed level\nG29 ; mesh bed leveling \nM204 T[machine_max_acceleration_travel] ; restore travel acceleration\nM104 S[first_layer_temperature] ; set extruder temp\nG92 E0\nG1 Y-2 X179 F2400\nG1 Z3 F720\nM109 S[first_layer_temperature] ; wait for extruder temp\n\n; intro line\nG1 X170 F1000\nG1 Z0.2 F720\nG1 X110 E8 F900\nG1 X40 E10 F700\nG92 E0\n\nM221 S95 ; set flow
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 40
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 255
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; threads = 8
; thumbnails = 16x16,220x124
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotoniclines
; top_infill_extrusion_width = 0.4
; top_solid_infill_acceleration = 800
; top_solid_infill_speed = 40
; top_solid_layers = 5
; top_solid_min_thickness = 0.7
; travel_acceleration = 0
; travel_speed = 150
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
